/**
 * lib/demo/data.ts — Sovereign OS v7.2
 *
 * Safe demo data for live walkthroughs and beta demos.
 * None of this is real user data — all names and figures are fictional.
 *
 * Covers: Projects, Memory, Relationships, Opportunities, Tasks.
 * These are the 5 keys swapped when Demo Mode activates.
 */

import type { Project, ProjectTask } from "@/lib/types/projects";
import type { MemoryItem } from "@/lib/types/memory";
import type { Person } from "@/lib/types/relationships";
import type { Opportunity } from "@/lib/types/opportunities";

const NOW = "2026-06-19T10:00:00.000Z";

// ── Projects ──────────────────────────────────────────────────────────────

export const DEMO_PROJECTS: Project[] = [
  {
    id: "demo-proj-1",
    title: "AI Revenue Systems Launch",
    status: "Active",
    category: "Agentic Systems",
    priority: "Critical",
    description: "Build and sell AI lead capture + appointment systems to local service businesses in Las Vegas.",
    objective: "Close 3 AI systems clients at $750–$1,500 each by end of Q3.",
    next_action: "Send discovery call invite to Priya Patel (med spa owner) — she expressed interest yesterday.",
    due_date: "2026-09-30",
    links: [],
    notes: "Focus on med spas, real estate, and home services first. Warm intros close faster than cold outreach.",
    created_at: "2026-06-01T09:00:00.000Z",
    updated_at: NOW,
  },
  {
    id: "demo-proj-2",
    title: "Content Growth Engine",
    status: "Active",
    category: "DWT",
    priority: "High",
    description: "Build a consistent content system across LinkedIn, YouTube, and X that drives inbound leads for AI services.",
    objective: "Publish 3x/week on LinkedIn, 1x/week on YouTube. Reach 500 followers by Aug 1.",
    next_action: "Record 3-minute breakdown video of the AI revenue systems offer — show the actual dashboard.",
    due_date: "2026-08-01",
    links: [],
    notes: "Best-performing angles: 'AI for your specific niche' and 'what I'd build for your business'.",
    created_at: "2026-06-05T09:00:00.000Z",
    updated_at: NOW,
  },
  {
    id: "demo-proj-3",
    title: "Sovereign OS Beta Prep",
    status: "Active",
    category: "Sovereign OS",
    priority: "High",
    description: "Harden Sovereign OS for a closed 5–10 person beta. Fix onboarding gaps, add demo mode, document everything.",
    objective: "Beta-ready by July 15. Onboard first 5 users with a live walkthrough call.",
    next_action: "Finish v7.2 Demo Mode implementation — enable demo hardening for live walkthroughs.",
    due_date: "2026-07-15",
    links: [],
    notes: "Focus on: demo flow, data safety, onboarding experience. The intelligence stack is production-ready.",
    created_at: "2026-06-10T09:00:00.000Z",
    updated_at: NOW,
  },
];

export const DEMO_PROJECT_TASKS: ProjectTask[] = [
  {
    id: "demo-task-1",
    project_id: "demo-proj-1",
    title: "Schedule discovery call with Priya Patel",
    status: "Todo",
    priority: "Critical",
    due_date: "2026-06-20",
    notes: "She runs a med spa — focus on lead capture + appointment booking use case.",
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-task-2",
    project_id: "demo-proj-1",
    title: "Build lead capture demo for med spa niche",
    status: "In Progress",
    priority: "High",
    due_date: "2026-06-25",
    notes: "Loom walkthrough showing the landing page → CRM → email follow-up sequence.",
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-task-3",
    project_id: "demo-proj-2",
    title: "Record AI Revenue Systems breakdown video",
    status: "Todo",
    priority: "High",
    due_date: "2026-06-21",
    notes: "3–5 minutes. Show what the actual system looks like for a business owner.",
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-task-4",
    project_id: "demo-proj-3",
    title: "Complete v7.2 Demo Mode",
    status: "In Progress",
    priority: "Critical",
    due_date: "2026-06-19",
    notes: "Badge, settings toggle, data swap, reset. Demo-safe for live calls.",
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-task-5",
    project_id: "demo-proj-3",
    title: "Write beta onboarding guide",
    status: "Todo",
    priority: "Medium",
    due_date: "2026-07-01",
    notes: "30-minute setup doc: projects → vision → contacts → memory → first focus session.",
    created_at: NOW,
    updated_at: NOW,
  },
];

// ── Memory Items ────────────────────────────────────────────────────────────

export const DEMO_MEMORY_ITEMS: MemoryItem[] = [
  {
    id: "demo-mem-1",
    title: "Closed first AI chatbot deal — $1,200 with med spa client",
    content: "Marcus Chen (MedGlow Aesthetics) signed off on an AI lead capture + chatbot system for $1,200. Needs SMS integration by July 15. This validated the offer at this price point — move forward with packaging it formally.",
    type: "Decision",
    tags: ["client", "win", "ai-systems"],
    relatedProjectIds: ["demo-proj-1"],
    relatedPeople: ["Marcus Chen"],
    importance: "High",
    source: "Manual",
    createdAt: "2026-06-15T14:00:00.000Z",
    updatedAt: "2026-06-15T14:00:00.000Z",
  },
  {
    id: "demo-mem-2",
    title: "Core insight: most local businesses lose leads in the follow-up gap",
    content: "The #1 problem for med spas, roofers, and home service companies isn't getting leads — it's the 3-day follow-up gap where most prospects go cold. AI follow-up sequences close this. This is the primary value prop for AI Revenue Systems.",
    type: "Idea",
    tags: ["strategy", "positioning", "ai-systems"],
    relatedProjectIds: ["demo-proj-1", "demo-proj-2"],
    relatedPeople: [],
    importance: "Critical",
    source: "Manual",
    createdAt: "2026-06-10T11:00:00.000Z",
    updatedAt: "2026-06-10T11:00:00.000Z",
  },
  {
    id: "demo-mem-3",
    title: "Best cold outreach: personalized Loom video + 3-touch sequence",
    content: "Tested multiple outreach methods. Personalized Loom video (90s walk-through of what I'd build for their business specifically) + 3-email sequence over 5 days outperforms everything else. Response rate ~12% vs ~2% for text-only.",
    type: "Decision",
    tags: ["outreach", "sales", "testing"],
    relatedProjectIds: ["demo-proj-1"],
    relatedPeople: [],
    importance: "High",
    source: "Manual",
    createdAt: "2026-06-08T09:00:00.000Z",
    updatedAt: "2026-06-08T09:00:00.000Z",
  },
  {
    id: "demo-mem-4",
    title: "Q3 revenue target: $5,000/month by September",
    content: "Working backwards: need 4 AI systems clients at $1,000–$1,500 each, or 3 clients + 1 retainer at $500/month. The retainer model (AI Content + Growth System) is the most sustainable — prioritize pitching this to closed clients first.",
    type: "Note",
    tags: ["goals", "revenue", "planning"],
    relatedProjectIds: ["demo-proj-1"],
    relatedPeople: [],
    importance: "Critical",
    source: "Manual",
    createdAt: "2026-06-01T09:00:00.000Z",
    updatedAt: "2026-06-01T09:00:00.000Z",
  },
  {
    id: "demo-mem-5",
    title: "David Kim intro — offered to introduce to his roofing network",
    content: "David Kim (AI/tech mentor) offered to introduce me to 3 roofing company owners in his network who are actively looking for lead gen solutions. Warm intros — reach out by end of June. Target: appointment setter system at $750–$1,000.",
    type: "Meeting",
    tags: ["networking", "referral", "roofing"],
    relatedProjectIds: ["demo-proj-1"],
    relatedPeople: ["David Kim"],
    importance: "High",
    source: "Manual",
    createdAt: "2026-06-17T16:00:00.000Z",
    updatedAt: "2026-06-17T16:00:00.000Z",
  },
];

// ── Relationships ────────────────────────────────────────────────────────────

export const DEMO_RELATIONSHIPS: Person[] = [
  {
    id: "demo-rel-1",
    name: "Marcus Chen",
    role: "Owner",
    organization: "MedGlow Aesthetics",
    email: "marcus@medglow.demo",
    phone: "",
    relationship_type: "Client",
    status: "Active",
    priority: "Critical",
    notes: "Closed $1,200 AI lead capture deal. Needs SMS integration by July 15. Open to retainer if system performs. Very responsive — prefers WhatsApp.",
    tags: ["client", "med-spa", "ai-systems"],
    related_project_ids: ["demo-proj-1"],
    related_opportunity_ids: ["demo-opp-1"],
    related_memory_ids: ["demo-mem-1"],
    last_contacted_at: "2026-06-15T14:00:00.000Z",
    next_follow_up_at: "2026-07-01",
    created_at: "2026-06-01T09:00:00.000Z",
    updated_at: NOW,
  },
  {
    id: "demo-rel-2",
    name: "Priya Patel",
    role: "Owner",
    organization: "Radiance Med Spa",
    email: "priya@radiancemedspa.demo",
    phone: "",
    relationship_type: "Prospect",
    status: "Follow Up",
    priority: "High",
    notes: "Met at local business networking event. Expressed strong interest in AI appointment booking. Has a 3-person front-desk team that spends most of their time on scheduling. Perfect fit for AI Appointment Setter offer.",
    tags: ["prospect", "med-spa", "appointment-setter"],
    related_project_ids: ["demo-proj-1"],
    related_opportunity_ids: ["demo-opp-2"],
    related_memory_ids: [],
    last_contacted_at: "2026-06-18T10:00:00.000Z",
    next_follow_up_at: "2026-06-20",
    created_at: "2026-06-18T10:00:00.000Z",
    updated_at: NOW,
  },
  {
    id: "demo-rel-3",
    name: "Sofia Rodriguez",
    role: "Brand Strategist",
    organization: "Freelance",
    email: "sofia@example.demo",
    phone: "",
    relationship_type: "Partner",
    status: "Active",
    priority: "Medium",
    notes: "Potential collaboration on content strategy. She builds brand identities for local businesses — complementary offer. Discussed a referral arrangement: she sends clients who need AI systems, I send clients who need brand work.",
    tags: ["collaboration", "content", "referral"],
    related_project_ids: ["demo-proj-2"],
    related_opportunity_ids: [],
    related_memory_ids: [],
    last_contacted_at: "2026-06-12T15:00:00.000Z",
    next_follow_up_at: "2026-06-26",
    created_at: "2026-06-05T09:00:00.000Z",
    updated_at: NOW,
  },
  {
    id: "demo-rel-4",
    name: "David Kim",
    role: "AI Advisor & Entrepreneur",
    organization: "Independent",
    email: "david@example.demo",
    phone: "",
    relationship_type: "Mentor",
    status: "Active",
    priority: "High",
    notes: "Mentor in AI space. 10 years building software products. Monthly check-in calls. Offered roofing network intros — follow up before June 30. Strong advocate for the Sovereign OS vision.",
    tags: ["mentor", "ai", "network"],
    related_project_ids: ["demo-proj-3"],
    related_opportunity_ids: [],
    related_memory_ids: ["demo-mem-5"],
    last_contacted_at: "2026-06-17T16:00:00.000Z",
    next_follow_up_at: "2026-06-30",
    created_at: "2026-04-01T09:00:00.000Z",
    updated_at: NOW,
  },
];

// ── Opportunities ─────────────────────────────────────────────────────────

export const DEMO_OPPORTUNITIES: Opportunity[] = [
  {
    id: "demo-opp-1",
    title: "Marcus Chen — AI Content + Growth System retainer",
    description: "Marcus's system is live and performing. Natural upsell to a $500/month retainer covering content scripts, repurposing, and monthly optimization calls.",
    type: "Revenue",
    status: "Active",
    score: 88,
    score_reasoning: "Existing client with proven trust, open budget, clear ROI already demonstrated. Very low friction close.",
    suggested_action: "Send retainer proposal after July 1 check-in call — show 30-day performance metrics from the lead capture system.",
    related_people: ["Marcus Chen"],
    related_project_ids: ["demo-proj-1"],
    related_memory_ids: ["demo-mem-1"],
    source: "manual",
    conversion: null,
    notes: "Ideal first retainer client. Use this deal to build out the retainer offer template.",
    created_at: "2026-06-16T09:00:00.000Z",
    updated_at: NOW,
  },
  {
    id: "demo-opp-2",
    title: "Priya Patel — AI Appointment Setter ($750)",
    description: "Radiance Med Spa spends 30+ hours/week on manual scheduling. AI appointment bot would reclaim that time and handle after-hours inquiries.",
    type: "Client",
    status: "Reviewing",
    score: 74,
    score_reasoning: "High pain point, warm relationship, clear offer fit. Blocked only by discovery call not yet booked.",
    suggested_action: "Book a 30-minute discovery call this week. Show the Calendly integration + SMS bot demo.",
    related_people: ["Priya Patel"],
    related_project_ids: ["demo-proj-1"],
    related_memory_ids: [],
    source: "manual",
    conversion: null,
    notes: "Don't oversell — let the problem sell itself. Ask: 'What happens when a lead calls after 6pm?'",
    created_at: "2026-06-18T11:00:00.000Z",
    updated_at: NOW,
  },
  {
    id: "demo-opp-3",
    title: "David Kim roofing referrals — AI Lead Capture ($1,000 each)",
    description: "David's roofing network contacts are actively looking for lead gen. Three warm introductions — each could be a $750–$1,000 AI Lead Capture System deal.",
    type: "Revenue",
    status: "Detected",
    score: 71,
    score_reasoning: "Warm intros convert 3–5x better than cold. Three potential deals in pipeline if executed before June 30.",
    suggested_action: "Ask David for the intros this week — he offered, strike while warm. Prep a 2-page PDF overview of the Lead Capture System.",
    related_people: ["David Kim"],
    related_project_ids: ["demo-proj-1"],
    related_memory_ids: ["demo-mem-5"],
    source: "detected",
    conversion: null,
    notes: "Time-sensitive — David mentioned he's traveling in July. Reach out before June 30.",
    created_at: NOW,
    updated_at: NOW,
  },
];

// ── Tasks (Productivity Panel format) ─────────────────────────────────────

export const DEMO_TASKS: Array<{ id: number; text: string; done: boolean }> = [
  { id: 1001, text: "Send discovery call invite to Priya Patel", done: false },
  { id: 1002, text: "Ask David Kim for roofing referral intros", done: false },
  { id: 1003, text: "Record AI Revenue Systems breakdown video (3 min)", done: false },
  { id: 1004, text: "Send July 1 check-in calendar invite to Marcus Chen", done: true },
  { id: 1005, text: "Draft retainer proposal template for existing clients", done: false },
];
